### ISSUE TITLE
Slack.RtmClient is not a constructor

### ISSUE THREAD

**Issue by BamaJoe411** [LukeMoll/slack-discord-bridge#8]
admin@vps208087:~/slack-discord-bridge$ node bot.js 
/home/admin/slack-discord-bridge/bot.js:8
var slackRTM = new Slack.RtmClient(slackKey.bot_token);
               ^

TypeError: Slack.RtmClient is not a constructor
    at Object.<anonymous> (/home/admin/slack-discord-bridge/bot.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by LukeMoll** [comment]
Someone can have a look at this, but I suspect it's because Slack deprecated the RTM API. What version of @slack/client are you running? It might have been introduced by [this commit](https://github.com/HackSoc/slack-discord-bridge/commit/1d9caa4195c16a1414046eb07024ac073b15205f).

I'm not sure whether the RTM API is deprecated or disabled, if it's the former then we can pin a version of @slack/client that still has the constructor. 

Regardless, this bridge is being slowly phased out in favour of a unified bridge that will replace this and [slack-irc](https://github.com/LukeMoll/slack-irc), so this won't be an issue for long. 

Thanks for bringing this up!

**Comment by BamaJoe411** [comment]
`├─┬ @slack/client@5.0.1`
`│ ├─┬ @slack/logger@1.0.0`
`│ │ └── @types/node@12.0.8`

**Comment by BamaJoe411** [comment]
No problem. I just need a bridge from discord to slack and vice versa. Thought I would give this a try but ran into this issue.
A friend helped me and found the issue was the case.
`  RTMClient: { [Function: RTMClient] loggerName: 'RTMClient' },`
`RTMClient` not `RtmClient`
Fixing that lead to more errors and I'm not familiar with node enough to continue fixing it.

**Comment by LucasAschenbach** [comment]
Just created a PR, migrating the slack bot to the new Events API which fixes this issue.
